### ISSUE TITLE
Adding graphs to the homepage

### ISSUE THREAD

**Issue by felskia** [developmentseed/scorecard#42]
could we add some fake data for users on the homepage? Let me know if you can't. I could always put in some images as a placeholder. 

<img width="604" alt="screen shot 2017-12-12 at 2 32 11 pm" src="https://user-images.githubusercontent.com/5421566/33904345-4833a3ec-df49-11e7-9a80-207311170c11.png">

**Comment by kamicut** [comment]
We added an image for now.
