### ISSUE TITLE
Handling user profiles

### ISSUE THREAD

**Issue by kamicut** [developmentseed/scorecard#8]
We need to figure out a way to handle extra pieces of profile information alongside OSM information. We will need an auxiliary database to hold things like "country", "contact", "IM username", etc. 

Questions:
1. How do we sync the OSM information with this extra profile information?
   - Should we fill the initial profile database with OSM information?
2. Should we render users that are not registered with `scorecard`?
   - How are users that are not registered rendered in the frontend? Are they prompted to register?
3. How do we handle different types of contact information, for example should "Rocket.chat" or "Slack" be primary IM fields, or should they be grouped in "IM"?
   - Since this could be different types of contact info in the leaderboards, should we display this contact field as a primary field or should it be a modal or highlight?

**Comment by sisskind** [comment]
@olearytd how do we do this in NOME? (Specifically first item)
